apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-client
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
        - name: mern-client
          image: maha487/mern-client:v2
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://server-service:5000"  # Ajout de la variable d'environnement pour le backend
