# Service pour le serveur
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: mern-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
  type: NodePort